- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Get site info and updating site details
      cisco.dnac.site_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: True
        dnac_log_level: DEBUG
        config_verify: True
        state: merged
        config:
          - site:
              area:
                name: "India"
                parent_name: 'Global'
            site_type: area
          - site:
              area:
                name: "Mysore"
                parent_name: 'Global/India'
            site_type: area
          - site:
              building:
                name: Palace1
                parent_name: "Global/India/Mysore"
                address: "Mysore ,India"
                latitude: 45.5
                longitude: 56.6
                country: ""
            site_type: building
          
