---
- name: Discover devices using multiple discovery specific credentials and delete all the discoveries
  hosts: localhost
  vars_files:
    - credentials.yml
  connection: local
  gather_facts: no
  vars:
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log: True
      dnac_log_level: DEBUG


#device discovery
  tasks:
    - name: Execute discovery of devices with global credentials only
      cisco.dnac.discovery_workflow_manager:
        <<: *dnac_login
        state: merged
        config_verify: True
        config:
            - discovery_name: Edge_1_206
              discovery_type: SINGLE
              ip_address_list:
              - 206.1.2.3
              global_credentials:
                cli_credentials_list:
                    - description: WLC
                      username: netadmin
                http_read_credential_list:
                    - description: http_read
                      username: wlcaccess
                http_write_credential_list:
                    - description: http_write
                      username: wlcaccess
                snmp_v3_credential_list:
                    - description: SNMPv3-credentials
                      username: v3Public
              net_conf_port: 830
              start_index: 1
              records_to_return: 100
              protocol_order: ssh
              retry: 5
              timeout: 3


#pause for 10 minutes before continuing the next task.
    - name: Wait for 10 minutes before provisioning
      pause:
        minutes: 12


# assigning device to site & provisoning.
    - name: Assign a wired device to a site & provisioning it
      cisco.dnac.provision_workflow_manager:
        <<: *dnac_login
        dnac_log: True
        state: merged
        config_verify: True
        config:
          - site_name_hierarchy: Global/USA/New York/BLD1
            management_ip_address: 206.1.2.3
          #   provisioning: false
          # - site_name_hierarchy: Global/USA/New York/BLD1
          #   management_ip_address: 206.1.2.4
          # - site_name_hierarchy: Global/USA/San Jose/BLD2
          #   management_ip_address: 205.1.2.2
            # provisoning: false

