#creating the sites
# - hosts: localhost
#   connection: local
#   gather_facts: no
#   vars_files:
#     - "credentials.yml"
#     - "buildings.yml"
#   tasks:
#     - name: Get site info and update site details for New York (5 floors)
#       cisco.dnac.site_workflow_manager:
#         dnac_host: "{{dnac_host}}"
#         dnac_username: "{{dnac_username}}"
#         dnac_password: "{{dnac_password}}"
#         dnac_verify: "{{dnac_verify}}"
#         dnac_port: "{{dnac_port}}"
#         dnac_version: "{{dnac_version}}"
#         dnac_debug: "{{dnac_debug}}"
#         dnac_log: True
#         dnac_log_level: DEBUG
#         config_verify: True
#         state: merged
#         config:
#           - site:
#               area:
#                 name: "India"
#                 parent_name: 'Global'
#             site_type: area
#           - site:
#               area:
#                 name: "Mysore"
#                 parent_name: 'Global/India'
#             site_type: area
#           - site:
#               building:
#                 name: "{{ item.0.name }}"
#                 parent_name: "{{ item.0.parent_name }}"
#                 address: "{{ item.0.address }}"
#                 latitude: "{{ item.0.latitude }}"
#                 longitude: "{{ item.0.longitude }}"
#                 country: "{{ item.0.country }}"
#             site_type: building
#           # Adding 5 floors for New York
#           - site:
#               floor:
#                 name: "Floor_{{ item.1 }}"
#                 parent_name: "{{ item.0.parent_name }}/{{ item.0.name }}"
#                 length: 103.23
#                 width: 75.1
#                 height: 50.22
#                 rf_model: 'Cubes And Walled Offices'
#                 floor_number: "{{ item.1 }}"
#                 units_of_measure: "feet"
#             site_type: floor
#       with_nested:
#         - "{{ buildings }}"
#         - "{{ range(1, 4) | list }}"  # 5 floors for New York
#       when: 
#         - "'India/Mysore' in item.0.parent_name"  # Ensure this matches the condition for New York


- hosts: localhost
  vars_files:
    - credentials.yml
  gather_facts: no
  connection: local
  vars:
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log_level: "DEBUG"
      dnac_log_append: True
  tasks:
  #assigning device creds
    - name: Create global device credentials.
      cisco.dnac.device_credential_workflow_manager:
        <<: *dnac_login
        dnac_log: True
        state: merged
        config_verify: True
        config:
        - global_credential_details:
            cli_credential:
            - description: WLC
              username: netadmin
              password: 'dnac123'
              enable_password: 'dnac123'
              # old_description:
              # old_username:
            snmp_v3:
            - auth_password: 'Cisco#123456789' # Atleast 8 characters
              auth_type: SHA # [SHA, MD5] (SHA is recommended)
              snmp_mode: AUTHPRIV # [AUTHPRIV, AUTHNOPRIV, NOAUTHNOPRIV]
              privacy_password: 'Cisco#1234567890' # Atleast 8 characters
              privacy_type: AES128 # [AE128, AE192, AE256]
              username: v3Public
              description: SNMPv3-credentials
              # old_description:
            https_read:
            - description: http_read
              username: wlcaccess
              password: 'Lablab#123'
              port: 443
              # old_description:
              # old_username:
            https_write:
            - description: http_write
              username: wlcaccess
              password: 'Lablab#123'
              port: 443
              #old_description:
              #old_username:

    - name: Assign global device credentials to a site.
      cisco.dnac.device_credential_workflow_manager:
        <<: *dnac_login
        dnac_log: True
        state: merged
        config_verify: True
        config:
        - assign_credentials_to_site:
            cli_credential:
              description: WLC
              username: netadmin
            snmp_v3:
              description: SNMPv3-credentials
              username: v3Public
            https_read:
              description: http_read
              username: wlcaccess
            https_write:
              description: http_write
              username: wlcaccess
            site_name: #the creds will be assigned directly to all the child nodes so be careful
            - Global/USA/New York
            - Global/USA/San Jose



    #global ip_pool creation,assigning to sites
    - name: Create global pool, reserve subpool and network functions
      cisco.dnac.network_settings_workflow_manager:
        <<: *dnac_login
        dnac_log: True
        # dnac_log_file_path: "{{ dnac_log_file_path }}"
        state: merged
        config_verify: True
        config:
        - global_pool_details:
            settings:
              ip_pool:
              - name: APPool_205
                pool_type: Generic
                ip_address_space: IPv4 #required when we are creating
                cidr: 205.1.208.0/20  #required when we are creating
                gateway: '205.1.208.1' #use this for updating
                dhcp_server_ips: [100.1.1.10] #use this for updating
                dns_server_ips: [100.1.1.10] #use this for updating
              - name: APPool_206
                pool_type: Generic
                ip_address_space: IPv4 #required when we are creating
                cidr: 206.1.208.0/20  #required when we are creating
                gateway: '206.1.208.1' #use this for updating
                dhcp_server_ips: [100.1.1.10] #use this for updating
                dns_server_ips: [100.1.1.10] #use this for updating

          reserve_pool_details:
          - site_name: Global/USA/new york
            name: APPool_sub_206
            pool_type: Generic
            ipv4_global_pool: 206.1.208.0/20
            ipv4_global_pool_name: APPool_206
            ipv4_prefix: True
            ipv4_prefix_length: 22
            ipv4_subnet: 206.1.208.0
            ipv4_gateway: 206.1.208.1
            ipv4_dns_servers: [100.1.1.10]
            ipv4_dhcp_servers: [100.1.1.10]
          - site_name: Global/USA/san jose
            name: APPool_sub_205
            pool_type: Generic
            ipv4_global_pool: 205.1.208.0/20
            ipv4_global_pool_name: APPool_205
            ipv4_prefix: True
            ipv4_prefix_length: 22
            ipv4_subnet: 205.1.208.0
            ipv4_gateway: 205.1.208.1
            ipv4_dns_servers: [100.1.1.10]
            ipv4_dhcp_servers: [100.1.1.10]


    #adding AAA,DHCP,Enabling telemetry
    - name: Create network functions
      cisco.dnac.network_settings_workflow_manager:
        <<: *dnac_login
        dnac_log: True
        # dnac_log_file_path: "{{ dnac_log_file_path }}"
        state: merged
        config_verify: True
        config:
        - network_management_details:
          - site_name: Global #the site where you want to add the servers
            settings:
              network_aaa:
                server_type: ISE
                pan_address: 10.197.156.78
                primary_server_address: 100.1.1.55
                protocol: RADIUS
              dhcp_server:
              - 10.197.156.94
              timezone: GMT
              wireless_telemetry:
                enable_wireless_telemetry: False
              message_of_the_day:
                banner_message: hello
                retain_existing_banner: True

